### ISSUE TITLE
Output for Manual Testing (Test Report)

### ISSUE THREAD

**Issue by viniciusmioto** [mastainvin/Xumes#64]
Hi @mastainvin,

I would like to know if the Test Report for manual testing has been removed. In previous versions, the manual test displayed a Test Report at the end, similar to the current automated test.

Thank you.

![image](https://github.com/mastainvin/Xumes/assets/60669449/cb3328f4-66db-4c22-9a50-cfaf67fb92cc)

**Comment by mastainvin** [comment]
Hi @viniciusmioto, it's still working on my side. Could you share the command used to start the manual tests?
Thank you.

**Comment by viniciusmioto** [comment]
I can run (play) the manual test. But the Test Report is not showed.

```gherkin
@manual
Scenario: Testing the pipe size manual
	Given first pipe at 0 and second pipe at 0.5
	When bird flies
	Then bird should have passed 2 pipes
```

```bash
python -m xumes play --features_path=./Tests/PipeSizeTest/features --steps_path=./Tests/PipeSizeTest/features/steps -i 4 --info --tags=manual --log
```

![image](https://github.com/mastainvin/Xumes/assets/60669449/67692cfd-8230-4a14-b3b9-6366c6ec1ecd)

**Comment by mastainvin** [comment]
Okay, so I tried both my version (imitation learning branch) and the 0.1.2 version. It seems that it has been fixed and will be merged by the end of the week. Is that too late for you?

**Comment by viniciusmioto** [comment]
No problem. Thank you very much!
